In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%pylab inline
plt.style.use('ggplot')
%matplotlib
from pandas.tools.plotting import scatter_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import ensemble
from sklearn.grid_search import GridSearchCV
import xgboost as xgb

Populating the interactive namespace from numpy and matplotlib
Using matplotlib backend: MacOSX

In [24]:
data_train = pd.read_csv('materials/train.tar.gz', compression='gzip', header=0, sep=';', quotechar='"' , nrows= 100000)
#data_test = pd.read_csv('materials/test-data.tar.gz', compression='gzip', header=0, sep=',', quotechar='"')
#data_sample = pd.read_csv('materials/sample_submission.csv')

In [3]:
#первые 5 строк для анализа
data_train.tail()

,train.csv,label,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,CG1,CG2,CG3,l1,l2,C11,C12
29989748,1.379538e+09,0.0,3.664390e+09,2.864383e+09,4403.0,25828.0,52.0,995.0,2.0,428.0,15.0,821.0,"273,248,249,213,252,380,382,381,93,96,88,50,53...",19098,NaN,55.0,0.0,0.0,103.0
29989749,1.379538e+09,0.0,1.725065e+09,3.324720e+09,3585.0,27942.0,68.0,995.0,0.0,361.0,15.0,49.0,"382,269,336,422,107,418,124,251,3,8,356,17,343...",NaN,NaN,2.0,0.0,0.0,104.0
29989750,1.379538e+09,0.0,9.231582e+08,1.240087e+09,5515.0,16713.0,95.0,3905.0,2.0,147.0,92.0,49.0,"273,213,252,242,377,382,381,375,374,219,217,22...",NaN,46594,0.0,0.0,1.0,106.0
29989751,1.379538e+09,0.0,3.498102e+09,2.837494e+09,112.0,5195.0,30.0,1699.0,0.0,451.0,99.0,49.0,"169,205,174,252,377,222,184,181,49,268,418,251...","15720,5365,16517,21434",NaN,0.0,0.0,1.0,104.0
29989752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(np.sum(data_train['label']==1)), \
print(np.sum(data_train['label']==0))

76302
29913450

(None, None)

In [5]:
# При загрузке данных в data_test все labels имеют значение -1. В data_sample все значения в столбце равны 0.5
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29989753 entries, 0 to 29989752
Data columns (total 19 columns):
train.csv    float64
label        float64
C1           float64
C2           float64
C3           float64
C4           float64
C5           float64
C6           float64
C7           float64
C8           float64
C9           float64
C10          float64
CG1          object
CG2          object
CG3          object
l1           float64
l2           float64
C11          float64
C12          float64
dtypes: float64(16), object(3)
memory usage: 4.2+ GB

In [ ]:
# количество строк-столбцов
data_train.shape

In [25]:
# разделение категориальных (object) и числовых (float) признаков
categorical_columns = [c for c in data_train.columns if data_train[c].dtype.name == 'object']
numerical_columns   = [c for c in data_train.columns if data_train[c].dtype.name != 'object']
print (categorical_columns)
print (numerical_columns)

['CG1', 'CG2', 'CG3']
['train.csv', 'label', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'l1', 'l2', 'C11', 'C12']

In [26]:
data_train_zeros = data_train[numerical_columns].fillna(value=0)
data_train_zeros.C1.astype(int64), \
data_train_zeros.C2.astype(int), \
data_train_zeros.C3.astype(int), \
data_train_zeros.C4.astype(int), \
data_train_zeros.C5.astype(int), \
data_train_zeros.C6.astype(int), \
data_train_zeros.C7.astype(int), \
data_train_zeros.C8.astype(int), \
data_train_zeros.C9.astype(int), \
data_train_zeros.C10.astype(int), \
data_train_zeros.C11.astype(int), \
data_train_zeros.C12.astype(int), \
data_train_zeros.l1.astype(int), \
data_train_zeros.l2.astype(int), \
data_train_zeros.label.astype(int)

(0        2733540231
 1        1964843810
 2         660357674
 3        2962648192
 4        1822613420
 5        2230694362
 6         149405498
 7        1651740157
 8        1207866034
 9        2132391877
 10       1207866034
 11       1822613420
 12       4192834470
 13       1895538078
 14       1822613420
 15       3404707152
 16       3829649523
 17       1895538078
 18       3242443620
 19       3367776458
 20       3120997466
 21       2263499518
 22       1992197611
 23       2662484318
 24       3367776458
 25       2263499518
 26        154126019
 27       2263499518
 28       2636489958
 29       3967702140
             ...
 99970    2152703172
 99971    1164155286
 99972    4290040407
 99973     159899881
 99974     129378700
 99975    2757636806
 99976    3711958893
 99977     706583238
 99978     233467351
 99979    1800030883
 99980    1697620617
 99981    1879732454
 99982     129378700
 99983    4159101765
 99984    3258395147
 99985    2672647980
 99986     233467351
 99987    2816802444
 99988    3493715811
 99989    2035323975
 99990    3829458288
 99991    4100731541
 99992    1712911892
 99993    2686027474
 99994     258088452
 99995    3268024376
 99996     296498570
 99997     230223638
 99998     230223638
 99999    3736678482
 Name: C1, Length: 100000, dtype: int64, 0        3500392421
 1        1232327635
 2        2066571765
 3        2373358995
 4         446973819
 5         462046911
 6        2008468818
 7         929846473
 8        1976462420
 9        3482861549
 10       1095451340
 11       2277192293
 12       3674600013
 13       4123103882
 14       2840661346
 15       3500392421
 16       1232327635
 17       4283011642
 18       3570349185
 19       2366864073
 20       1695423685
 21       1314736296
 22       3649618909
 23       3747633635
 24       4116346656
 25        402681528
 26       1232327635
 27       2064356622
 28       1931060789
 29       3747633635
             ...
 99970     247901565
 99971    3442864275
 99972    3853684959
 99973    1190924507
 99974    3502761956
 99975    2364358810
 99976     556782036
 99977     218913392
 99978    1723524333
 99979     801161488
 99980    1087369623
 99981    1106978045
 99982    1079980451
 99983    3105428525
 99984     218892432
 99985     366839812
 99986    3553911068
 99987    1673977111
 99988     683565777
 99989     218892432
 99990    1212717362
 99991    3244478402
 99992    2905632979
 99993    1801169547
 99994     721220730
 99995      84719471
 99996    1519340062
 99997    1882352990
 99998    1325894964
 99999     538296677
 Name: C2, Length: 100000, dtype: int64, 0        4454
 1        2081
 2         602
 3        4018
 4        2081
 5        4781
 6        5454
 7        5678
 8        3353
 9        3595
 10       2360
 11       2081
 12       5704
 13       2360
 14       1590
 15       4454
 16       2081
 17       3353
 18        109
 19       4943
 20       5318
 21        465
 22       3952
 23       3542
 24       2360
 25       2081
 26       2081
 27        393
 28       5728
 29       3542
          ...
 99970    2081
 99971     911
 99972    4454
 99973    6204
 99974    1761
 99975    5551
 99976     257
 99977    4454
 99978    2568
 99979     400
 99980    3655
 99981    5236
 99982    2488
 99983    5126
 99984     400
 99985     259
 99986    3015
 99987    3634
 99988    4176
 99989     400
 99990    5182
 99991    2360
 99992    3671
 99993    4548
 99994    5110
 99995     515
 99996    1880
 99997     393
 99998    6319
 99999     259
 Name: C3, Length: 100000, dtype: int64, 0        15573
 1         2547
 2        29581
 3        36969
 4        23457
 5        16144
 6        24226
 7         4314
 8         4241
 9         6952
 10       33431
 11       21050
 12         422
 13       33431
 14        4057
 15       15573
 16        2547
 17       17918
 18       13832
 19         736
 20        7157
 21        6603
 22       25033
 23       19246
 24       16554
 25       17110
 26        2547
 27       23166
 28       31367
 29       19246
          ...
 99970    21795
 99971    34215
 99972     7162
 99973    13127
 99974    36319
 99975    14987
 99976    20893
 99977     6711
 99978    12522
 99979    23137
 99980       36
 99981    24711
 99982    11549
 99983     6394
 99984    31673
 99985     9671
 99986    16737
 99987    19029
 99988     2743
 99989    31673
 99990    27999
 99991       47
 99992    20974
 99993    15166
 99994    17124
 99995    32954
 99996    24451
 99997    21702
 99998    11508
 99999     7700
 Name: C4, Length: 100000, dtype: int64, 0        11
 1        11
 2        29
 3        30
 4        35
 5         6
 6        11
 7        10
 8        88
 9        83
 10       88
 11       35
 12        1
 13       88
 14       30
 15       11
 16       11
 17       88
 18        0
 19       31
 20       11
 21       52
 22       11
 23        6
 24       31
 25       52
 26       11
 27       52
 28       19
 29        6
          ..
 99970    14
 99971    95
 99972    11
 99973    92
 99974    52
 99975    11
 99976    54
 99977    52
 99978    30
 99979    13
 99980    11
 99981     1
 99982    30
 99983    64
 99984    13
 99985    54
 99986    52
 99987    88
 99988    11
 99989    13
 99990    30
 99991    87
 99992    10
 99993    30
 99994    13
 99995    13
 99996    13
 99997    13
 99998    13
 99999    88
 Name: C5, Length: 100000, dtype: int64, 0         995
 1         995
 2         995
 3         995
 4         995
 5        1694
 6         995
 7         995
 8         995
 9         995
 10        995
 11        995
 12       1694
 13        995
 14        995
 15        995
 16        995
 17        995
 18       3905
 19        995
 20        995
 21        995
 22        995
 23        551
 24        995
 25        995
 26        995
 27        995
 28        995
 29        995
          ...
 99970     995
 99971    3905
 99972     995
 99973    2355
 99974     995
 99975    3756
 99976     995
 99977     995
 99978     995
 99979     995
 99980    3403
 99981    2239
 99982     995
 99983    3905
 99984     995
 99985     995
 99986     995
 99987    1034
 99988     995
 99989     995
 99990     995
 99991     995
 99992     995
 99993    3403
 99994     995
 99995     995
 99996     995
 99997     995
 99998     995
 99999     995
 Name: C6, Length: 100000, dtype: int64, 0        2
 1        2
 2        0
 3        2
 4        0
 5        0
 6        0
 7        2
 8        2
 9        2
 10       2
 11       0
 12       2
 13       2
 14       0
 15       2
 16       2
 17       2
 18       2
 19       0
 20       2
 21       2
 22       2
 23       2
 24       0
 25       2
 26       2
 27       2
 28       2
 29       2
         ..
 99970    2
 99971    2
 99972    2
 99973    0
 99974    0
 99975    2
 99976    2
 99977    2
 99978    2
 99979    0
 99980    0
 99981    0
 99982    0
 99983    2
 99984    2
 99985    0
 99986    2
 99987    2
 99988    2
 99989    2
 99990    2
 99991    0
 99992    0
 99993    2
 99994    0
 99995    2
 99996    0
 99997    2
 99998    2
 99999    0
 Name: C7, Length: 100000, dtype: int64, 0        176
 1        361
 2        468
 3          8
 4        452
 5        390
 6        313
 7        419
 8        177
 9        419
 10       177
 11       452
 12       390
 13       177
 14       452
 15       176
 16       361
 17       177
 18       147
 19       248
 20       361
 21       452
 22       176
 23       362
 24       248
 25       452
 26       361
 27       452
 28       419
 29       365
         ...
 99970    419
 99971    214
 99972    361
 99973    390
 99974    452
 99975    313
 99976    341
 99977    468
 99978    376
 99979    293
 99980    313
 99981    462
 99982    452
 99983    147
 99984    293
 99985    341
 99986    376
 99987    177
 99988     70
 99989    293
 99990    451
 99991    282
 99992    293
 99993    451
 99994    293
 99995    419
 99996    293
 99997    293
 99998    293
 99999    177
 Name: C8, Length: 100000, dtype: int64, 0        15
 1        15
 2        15
 3        15
 4        15
 5        22
 6        15
 7        15
 8        15
 9        15
 10       15
 11       15
 12       22
 13       15
 14       15
 15       15
 16       15
 17       15
 18       53
 19       15
 20       15
 21       15
 22       15
 23       20
 24       15
 25       15
 26       15
 27       15
 28       15
 29        1
          ..
 99970    15
 99971    63
 99972    15
 99973    39
 99974    15
 99975    73
 99976    15
 99977    15
 99978    15
 99979    15
 99980    63
 99981    43
 99982    15
 99983    92
 99984    15
 99985    15
 99986    15
 99987     1
 99988    15
 99989    15
 99990    15
 99991    15
 99992    15
 99993    95
 99994    15
 99995    15
 99996    15
 99997    15
 99998    15
 99999    15
 Name: C9, Length: 100000, dtype: int64, 0         671
 1         802
 2         758
 3          67
 4         821
 5         822
 6         821
 7          24
 8           5
 9         479
 10          5
 11        821
 12         49
 13         48
 14        821
 15        251
 16        802
 17         48
 18         49
 19       1387
 20       1306
 21        821
 22        491
 23        313
 24       1387
 25        821
 26        802
 27        821
 28        490
 29        548
          ...
 99970      50
 99971     596
 99972     751
 99973    1106
 99974    1292
 99975     821
 99976      34
 99977     802
 99978      49
 99979      49
 99980     802
 99981     821
 99982    1292
 99983     747
 99984     802
 99985    1326
 99986      49
 99987    1106
 99988    1279
 99989      49
 99990     821
 99991      50
 99992     802
 99993     821
 99994     821
 99995      44
 99996     802
 99997     821
 99998     821
 99999     758
 Name: C10, Length: 100000, dtype: int64, 0        0
 1        0
 2        0
 3        0
 4        0
 5        1
 6        0
 7        0
 8        0
 9        0
 10       0
 11       0
 12       1
 13       0
 14       0
 15       0
 16       0
 17       0
 18       1
 19       0
 20       0
 21       0
 22       0
 23       1
 24       0
 25       0
 26       0
 27       0
 28       0
 29       0
         ..
 99970    0
 99971    1
 99972    0
 99973    1
 99974    0
 99975    1
 99976    0
 99977    0
 99978    0
 99979    0
 99980    1
 99981    1
 99982    0
 99983    1
 99984    0
 99985    0
 99986    0
 99987    1
 99988    0
 99989    0
 99990    0
 99991    0
 99992    0
 99993    1
 99994    0
 99995    0
 99996    0
 99997    0
 99998    0
 99999    0
 Name: C11, Length: 100000, dtype: int64, 0        106
 1        106
 2        103
 3        106
 4        106
 5        105
 6        105
 7        104
 8        106
 9        105
 10       106
 11       106
 12       104
 13       105
 14       106
 15       105
 16       106
 17       105
 18       103
 19       105
 20       106
 21       106
 22       104
 23       104
 24       105
 25       106
 26       106
 27       106
 28       106
 29       105
         ...
 99970    105
 99971    106
 99972    106
 99973    104
 99974    104
 99975    104
 99976    104
 99977    106
 99978    104
 99979    104
 99980    104
 99981    103
 99982    104
 99983    104
 99984    103
 99985    105
 99986    104
 99987    105
 99988    106
 99989    100
 99990    105
 99991    105
 99992    103
 99993    105
 99994    104
 99995    105
 99996    104
 99997    105
 99998    105
 99999    104
 Name: C12, Length: 100000, dtype: int64, 0         32
 1          1
 2        119
 3          0
 4          5
 5          3
 6          0
 7         26
 8         52
 9          0
 10        42
 11         0
 12         2
 13        12
 14         3
 15        41
 16         7
 17        13
 18         1
 19        27
 20         8
 21         0
 22         1
 23         7
 24        20
 25         0
 26        21
 27        14
 28         5
 29         0
         ...
 99970      0
 99971      1
 99972      0
 99973      0
 99974      3
 99975      0
 99976     22
 99977     13
 99978      0
 99979      0
 99980      1
 99981      0
 99982      5
 99983      0
 99984      2
 99985    187
 99986      0
 99987      0
 99988    807
 99989      1
 99990      7
 99991     16
 99992      0
 99993    128
 99994      1
 99995      0
 99996      1
 99997     31
 99998      8
 99999      2
 Name: l1, Length: 100000, dtype: int64, 0        0
 1        0
 2        0
 3        0
 4        0
 5        0
 6        0
 7        0
 8        0
 9        0
 10       0
 11       0
 12       0
 13       0
 14       0
 15       0
 16       0
 17       0
 18       0
 19       0
 20       0
 21       0
 22       0
 23       0
 24       0
 25       0
 26       0
 27       0
 28       0
 29       0
         ..
 99970    0
 99971    0
 99972    0
 99973    0
 99974    0
 99975    0
 99976    0
 99977    0
 99978    0
 99979    0
 99980    0
 99981    0
 99982    0
 99983    0
 99984    0
 99985    0
 99986    0
 99987    0
 99988    0
 99989    0
 99990    0
 99991    0
 99992    0
 99993    0
 99994    0
 99995    0
 99996    0
 99997    0
 99998    0
 99999    0
 Name: l2, Length: 100000, dtype: int64, 0        0
 1        0
 2        0
 3        0
 4        0
 5        0
 6        0
 7        0
 8        0
 9        0
 10       0
 11       0
 12       0
 13       0
 14       0
 15       0
 16       0
 17       0
 18       0
 19       0
 20       0
 21       0
 22       0
 23       0
 24       0
 25       0
 26       0
 27       0
 28       0
 29       0
         ..
 99970    0
 99971    0
 99972    0
 99973    0
 99974    0
 99975    0
 99976    0
 99977    0
 99978    0
 99979    0
 99980    0
 99981    0
 99982    0
 99983    0
 99984    0
 99985    0
 99986    0
 99987    0
 99988    0
 99989    0
 99990    0
 99991    0
 99992    0
 99993    0
 99994    0
 99995    0
 99996    0
 99997    0
 99998    0
 99999    0
 Name: label, Length: 100000, dtype: int64)

In [24]:
 data_train_zeros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29989753 entries, 0 to 29989752
Data columns (total 16 columns):
train.csv    float64
label        float64
C1           float64
C2           float64
C3           float64
C4           float64
C5           float64
C6           float64
C7           float64
C8           float64
C9           float64
C10          float64
l1           float64
l2           float64
C11          float64
C12          float64
dtypes: float64(16)
memory usage: 3.6 GB

In [27]:
# выделение столбец label в отдельную переменную. Удаление label из общего датасета в трайн и тест
data_train_label = data_train['label']
#data_test_label = data_test['label']
data_train_target = data_train_zeros.drop(columns=[ 'train.csv','label'] ,axis = 1)
#data_test_target = data_test.drop(columns=['test.csv', 'CG1', 'CG2','CG3' , 'label', 'Unnamed: 0', 'C11', 'l2'])

In [139]:
# статистика по категориальным признакам
data_train_target[categorical_columns].describe()

                                              CG1       CG2      CG3
count                                    29895541  10489375  3084482
unique                                    2096665    148995   239352
top     99,154,155,76,412,122,139,333,332,335,334     30009    45509
freq                                       309280     48443   124520

In [46]:
# корреляция признаков на scatter_matrix
scatter_matrix(data_train[numerical_columns], alpha = 0.5, figsize = (20,20))

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x1a25726a90>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2a0499b0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a28b3cf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29f55630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29f7ccc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29f7ccf8>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29cb3a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29ce30f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29d0a780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29e85e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29eb34e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29edab70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29f0c240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29f318d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29fadf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a29fde630>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a2a004cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2a3e8390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2a40fa20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2a4410f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2bbab780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2bbd4e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2bc054e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2bc29b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2df93240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2dfba8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2dfe1f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e011630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e03acc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e06a390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e090a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e0c20f0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a2e0e9780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e111e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e1424e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e167b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e19a240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e1c18d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e1e7f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e218630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e23fcc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e26f390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e295a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e2c70f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e2ed780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e314e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e3464e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a2e36eb70>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a2e39e240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3d9fd8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3da27f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3da56630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3da81cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dab2390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dad8a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3db0a0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3db31780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3db57e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3db884e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dbb1b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dbe2240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dc0a8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dc334e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dc59b70>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3dc8a240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dcb38d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dcd8f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dd08630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dd31cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dd64390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dd8ba20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ddbc0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dde4780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3de0be10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3de3b4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3de63b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3de97240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3debd8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dee5f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3df17630>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3df3dcc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3df6e390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3df95a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dfc80f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3dfef780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e017e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e0494e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e070b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e0a1240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e0c88d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e0f0f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e120630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e14bcc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e17a390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e1a1a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e1d30f0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3e1fb780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e222e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e2544e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e27bb70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e2ac240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e2d38d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e2fcf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e32e630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e353cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e386390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e3aca20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e3dd0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e407780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e430e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e4604e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e487b70>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3e4b8240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e4df8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e506f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e539630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e561cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e591390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e5b8a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e5ea0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e610780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e639e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e66b4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e692b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e6c3240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e6ec8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e714f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e744630>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3e76ccc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e79b390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e7c4a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e7f70f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e81e780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e846e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e8794e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e89db70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e8cd240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e8f68d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e91ff60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e950630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e977cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e9ac390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e9d1a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ea020f0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3ea2b780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ea51e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ea804e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eaa9b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eadd240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eb048d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eb2cf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eb5d630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eb82cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ebb3390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ebdba20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ec0d0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ec36780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ec5be10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ec8e4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ecb5b70>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3ece5240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ed0e8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ed38f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ed67630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ed90cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3edc0390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ede7a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ee190f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ee41780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ee69e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ee984e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eec0b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eef2240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ef198d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ef43f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3ef74630>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3ef9acc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3efcc390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3eff4a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f0250f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f04c780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f075e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f0a54e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f0cab70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f0fe240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f1268d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f14bf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f17f630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f1a7cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f1d6390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f1fea20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f2310f0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3f258780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f27fe10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f2b14e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f2d7b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f30a240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f3308d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f359f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f389630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f3b1cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f3e1390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f40ba20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f43b0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f463780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f48be10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f4bb4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f4e5b70>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3f514240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3e8cf8d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f564f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f594630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f5bbcc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f5f0390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f616a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f6470f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f670780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f696e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f6c64e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f6f0b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f723240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f7488d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f771f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f7a2630>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3f7c9cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f7fb390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f821a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f8540f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f87c780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f8a3e10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f8d34e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f8fcb70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f92d240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f9548d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f97bf60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f9ab630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3f9d4cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fa07390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fa2da20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fa5f0f0>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x1a3fa87780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3faafe10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fadf4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fb07b70>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fb38240>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fb618d0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fb88f60>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fbb9630>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fbe0cc0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fc10390>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fc38a20>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fc6a0f0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fc91780>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fcbbe10>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fced4e0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x1a3fd11b70>]],
      dtype=object)

In [49]:
# посмотрим на корреляцию все признаков между собой по таблице
# признаки l2 и С11 содержат нулевые значения

In [ ]:
# посмотрим сколько НЕ пустых значения в каждом столбце поотдельности с помощью метода count и axis = 0, который указывает, что мы 
# дыигаемся сверху вниз, а не слева направо (axis = 1)
data_train_target[numerical_columns].count(axis = 1).shape, \
data_train_target[numerical_columns].shape

In [ ]:
# попробуем заменить пропущенные значения нулями, средними значениями и самыми популярными значениями
# категориальные признаки пока что не используем. Попробуем обучиться без них и посмотреть на качество
# уберем признаки l2 и С11 так как они почти все нулевые и очень сильно коррелируют с целевым признаком label.
#  Дальнейшая работа будет без признаков типа оbject и количественных признаков l2 и C11

In [51]:
# масшатбирование признаков
# Построим матрицу scatter_matrix чтобы посмотреть на масштабируемость значений. Возьмем на примере признаков C1, C12, C7
# Посмотрим на признаках 
data_numeric = pd.DataFrame(data_train_target, columns=numerical_columns)
list_cols = ['C1', 'C2', 'C7']
scatter_matrix(data_numeric[list_cols], alpha=0.5, figsize=(7, 7))
plt.show()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.

In [19]:
#  На графике по трем признакам из общего массива видно, что значения признаков очень различаются по масштабу
# Далее выполняется масштабирование признаков

In [52]:
scaler_data = StandardScaler()
scaler_data.fit_transform(data_train_target, data_train_label)
data_train_scaled = scaler_data.transform(data_train_target, data_train_label)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:675: DeprecationWarning: The parameter y on transform() is deprecated since 0.19 and will be removed in 0.21
  DeprecationWarning)

In [18]:
data_numeric = pd.DataFrame(data_train_scaled, columns=numerical_columns)
list_cols = ['C1', 'C2', 'C7']
scatter_matrix(data_numeric[list_cols], alpha=0.5, figsize=(7, 7))
plt.show()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
# Видно что признаки отмасштабировались. Попробуем посмотреть на балансировку классов и стратификацию выборки
#(написать поподробнее про стратифкацию выборки)

In [53]:
print(np.sum(data_train_label==1)), \
print(np.sum(data_train_label==0))

207
99793

(None, None)

In [ ]:
# Просуммировав количество истинных и ложных ответов видно что классы плохо сбалансированы. Воспользуемся масштабированнием классов. 
# Попрбуем обучить наши данные на после масштабирования. Посмотрим как обучается модель
# Используется логистическая регрессия. Метрика качества log loss

In [ ]:
(X_train, 
 X_test, 
 y_train, y_test) = train_test_split(data_train_scaled, data_train_label, 
                                     test_size=0.3, 
                                     random_state=0)
(X_train_corr, 
 X_test_corr, 
 y_train_corr, y_test_corr) = train_test_split(data_train_target_corr, data_train_label, 
                                     test_size=0.3, 
                                     random_state=0)

In [56]:
%time
model = xgb.XGBClassifier()
model.fit(X_train_corr, y_train_corr)
clf_probs = model.predict(X_test_corr)
score = log_loss(y_test_corr, clf_probs)
print(score)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.25 µs
0.06907755278982236

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [37]:
data_train_target.corr()

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,l1,l2,C11,C12
C1,1.000000,0.001444,-0.007491,-0.000372,-0.005403,-0.005078,-0.023310,0.016382,0.005040,0.028486,-0.018221,0.014615,0.000285,-0.006468
C2,0.001444,1.000000,0.063388,0.046496,0.035080,0.000742,-0.028937,-0.006504,-0.002388,0.010639,-0.018018,0.006397,0.000495,-0.001201
C3,-0.007491,0.063388,1.000000,-0.053923,0.041276,0.098702,0.122151,0.038692,0.099000,0.002508,-0.019761,0.011311,0.134419,0.054022
C4,-0.000372,0.046496,-0.053923,1.000000,-0.063072,-0.053684,-0.003842,-0.004350,-0.048386,0.015705,-0.080024,-0.010603,-0.058111,-0.055920
C5,-0.005403,0.035080,0.041276,-0.063072,1.000000,0.084152,0.074734,-0.113434,0.082684,0.015332,0.091126,0.025278,0.105186,0.176835
C6,-0.005078,0.000742,0.098702,-0.053684,0.084152,1.000000,0.039063,-0.021305,0.659855,0.003189,-0.026749,0.002122,0.748827,-0.120263
C7,-0.023310,-0.028937,0.122151,-0.003842,0.074734,0.039063,1.000000,-0.029982,0.033329,0.007687,-0.033720,0.004453,0.052940,0.124943
C8,0.016382,-0.006504,0.038692,-0.004350,-0.113434,-0.021305,-0.029982,1.000000,0.021794,-0.025988,0.026012,0.018897,0.086522,0.031650
C9,0.005040,-0.002388,0.099000,-0.048386,0.082684,0.659855,0.033329,0.021794,1.000000,-0.003599,-0.026554,0.006434,0.733334,-0.094871
C10,0.028486,0.010639,0.002508,0.015705,0.015332,0.003189,0.007687,-0.025988,-0.003599,1.000000,-0.020845,-0.008069,0.000753,-0.009443
l1,-0.018221,-0.018018,-0.019761,-0.080024,0.091126,-0.026749,-0.033720,0.026012,-0.026554,-0.020845,1.000000,0.023707,-0.037858,0.049121
l2,0.014615,0.006397,0.011311,-0.010603,0.025278,0.002122,0.004453,0.018897,0.006434,-0.008069,0.023707,1.000000,0.008798,0.028305
C11,0.000285,0.000495,0.134419,-0.058111,0.105186,0.748827,0.052940,0.086522,0.733334,0.000753,-0.037858,0.008798,1.000000,-0.123992
C12,-0.006468,-0.001201,0.054022,-0.055920,0.176835,-0.120263,0.124943,0.031650,-0.094871,-0.009443,0.049121,0.028305,-0.123992,1.000000

In [39]:
data_train_target_corr = data_train_target.drop(columns=['C11', 'l2'])

In [42]:
data_train_target_corr.head()

           C1          C2    C3     C4  C5   C6  C7   C8  C9  C10   l1  C12
0  2733540231  3500392421  4454  15573  11  995   2  176  15  671   32  106
1  1964843810  1232327635  2081   2547  11  995   2  361  15  802    1  106
2   660357674  2066571765   602  29581  29  995   0  468  15  758  119  103
3  2962648192  2373358995  4018  36969  30  995   2    8  15   67    0  106
4  1822613420   446973819  2081  23457  35  995   0  452  15  821    5  106

In [60]:
# Исключив признаки C11 и l2
regressor = LogisticRegression()
log_regressor = regressor.fit(X_train_corr, y_train_corr)
clf_probs = log_regressor.predict(X_test_corr)
score_log = log_loss(y_test_corr, clf_probs)
print(score)

0.06907755278982236

In [57]:
# Обучение на логичстической регрессии и на xgboost

In [62]:

def write_answer(result):
    with open("result.csv", "w") as fout:
        fout.write(str(result))
write_answer(score_log)